version: '2'
volumes:
  mysql_data: {}
  redis_data: {}
services:
  web:
    build: .
#    command:
#      - /bin/bash
#      - -c
#      - |
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/foreign_science_tech
      - ${IMGGE_PATH}:/foreign_science_tech/public/images
      - ${FILE_PATH}:/foreign_science_tech/public/files
      - ${MEDIA_PATH}:/foreign_science_tech/public/medias
    ports:
      - "3000:3000"
    depends_on:
      - db-mysql
      - db-redis
    env_file: .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_COMMEN_HOST=${MYSQL_COMMEN_HOST}
      - MYSQL_COMMEN_DATABASE=${MYSQL_COMMEN_DATABASE}
      - MYSQL_COMMEN_USER=${MYSQL_COMMEN_USER}
      - MYSQL_COMMEN_PORT=${MYSQL_COMMEN_PORT}
      - MYSQL_COMMEN_PASSWORD=${MYSQL_COMMEN_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  sidekiq:
    build: .
    volumes:
      - .:/foreign_science_tech
    ports: []
    depends_on:
      - db-mysql
      - db-redis
    env_file: .env
    command: bundle exec sidekiq -C config/sidekiq.yml
  db-mysql:
    image: mysql:5.7.17
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER= ${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - "./mysql_data/db:/var/lib/mysql"
      - "./mysql_data/db:/var/run/mysqld"
#      - "./mysql_data/conf/my.cnf:/etc/my.cnf"
#      - "./mysql_data/init:/docker-entrypoint-initdb.d/"
    ports:
      - "${MYSQL_PORT}:3306"
    command: ['mysqld', '--character-set-server=utf8']
    tty: true
  db-redis:
    image: redis:4.0.8
    container_name: redis
    restart: unless-stopped
    hostname: ${REDIS_HOST}
    env_file: .env
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf:rw
      - ./redis_data:/data:rw
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server /etc/redis/redis.conf --appendonly yes
    tty: true