version: '2'
volumes:
  mysql_data: {}
  redis_data: {}
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/foreign_science_tech
      - ${IMGGE_PATH}:/foreign_science_tech/public/images
      - ${FILE_PATH}:/foreign_science_tech/public/files
      - ${MEDIA_PATH}:/foreign_science_tech/public/medias
    ports:
      - "3000:3000"
    env_file: .env