:verbose: false
:concurrency: 5 # 并发数
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log # 输出的日志地址
:timeout: 30
:queues:
  - default # 写在队列参数中的, 表示让 sidekiq 处理这个 queue
  - monitor_instances
  - process_status
  - uncompleted_tasks
  - t_sk_job_instances
 
development:
:concurrency: 5
staging:
:concurrency: 5
production:
:concurrency: 5
