MonitorInstancesJob:
  cron: '0 */2 * * * Asia/Shanghai'
  class: MonitorInstancesJob
#ProcessStatusJob:
#  cron: '*/1 * * * * Asia/Shanghai'
#  class: ProcessStatusJob
#UncompletedTasksJob:
#  cron: '0 */4 * * * Asia/Shanghai'
#  class: UncompletedTasksJob
MonitorSidekiqJob:
  cron: '* */12 * * * Asia/Shanghai'
  class: MonitorSidekiqJob